# Generated by Django 3.0.14 on 2022-11-23 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('transaction_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=52)),
                ('cpf', models.CharField(max_length=11)),
                ('card_details', models.CharField(max_length=12)),
                ('time', models.TimeField()),
                ('bussiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_transactions', to='businesses.Business')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_of_this_type', to='transaction_types.Transaction_type')),
            ],
        ),
    ]
