# Generated by Django 3.0.14 on 2022-11-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='bussiness',
            new_name='business',
        ),
    ]
